name: kasetsart-stack

services:
  mysql:
    image: mariadb:10
    restart: unless-stopped
    env_file: ./.env
    command: ["mysqld","--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [appnet]

  strapi:
    build:
      context: ../strapi
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: [mysql]
    env_file: ./.env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    networks: [appnet]
    volumes:
      - strapi_uploads:/app/public/uploads

  next:
    build:
      context: ../nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      NODE_ENV: production
      API_URL: ${STRAPI_INTERNAL_URL}
      AUTH_TRUST_HOST: "true"
    depends_on: [strapi]
    networks: [appnet]

  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: unless-stopped
    env_file: ./.env
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 256M
      # --- ส่วนสำคัญที่เพิ่มเข้ามา ---
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    depends_on: [mysql]
    networks: [appnet]

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on: [next, strapi, phpmyadmin]
    networks: [appnet]

networks:
  appnet:

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
  strapi_uploads: