version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kasetsart_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - kasetsart-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: kasetsart_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - kasetsart-network

  strapi:
    build:
      context: ../strapi
      dockerfile: Dockerfile
      target: production
    container_name: kasetsart_strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      HOST: 0.0.0.0
      PORT: 1337
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      NODE_ENV: production
      PUBLIC_URL: ${PUBLIC_BASE_URL}/strapi
    ports:
      - "1337:1337"
    volumes:
      - strapi_uploads:/app/public/uploads
      - strapi_data:/app/.tmp
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - kasetsart-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs:
    build:
      context: ../nextjs
      dockerfile: Dockerfile
    container_name: kasetsart_nextjs
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      STRAPI_INTERNAL_URL: ${STRAPI_INTERNAL_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      API_BASE: ${API_BASE}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    restart: unless-stopped
    networks:
      - kasetsart-network

  caddy:
    image: caddy:alpine
    container_name: kasetsart_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs
      - strapi
      - phpmyadmin
    restart: unless-stopped
    networks:
      - kasetsart-network

networks:
  kasetsart-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  strapi_uploads:
    driver: local
  strapi_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
